# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          extended: true
      - run: hugo
      - run: pwd
      - name: Create site search index
        run: cat public/index.json | node scripts/lunr/site-index.js > public/js/site-search-index.json
      - name: Create blog search index
        run: cat public/blog/index.json | node scripts/lunr/blog-index.js > public/js/blog-search-index.json
      - name: Copy atom feed in place
        run: cp public/blog/atom.xml public/atom.xml
      - name: Copy more feeds in place
        run: mkdir public/feed/ && cp public/blog/rss.xml public/feed/index.xml
      - name: Deploy
        run:  |
          cp -R public $HOME/public
          cd $HOME
          git config --global user.email "gh@gh-actions"
          git config --global user.name "GH Action"

          mkdir release
          cd release

          echo "Shallow-cloning release\n"
          git clone --no-checkout --quiet --branch=release --depth 1 https://github.com/${GITHUB_ACTOR}/${GITHUB_REPOSITORY}.git .
          cp -Rf $HOME/public/* .

          echo "Adding all changes and committing\n"
          git add -A .
          git commit -m "Action no $GITHUB_RUN_NUMBER" > /dev/null
          echo "Pushing built site\n"
          git push -fq origin release > /dev/null

          echo "Done updating release\n"
